version: "3"

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - LISTEN_ADDR=gateway:6000
      
  node1:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - LISTEN_ADDR=node1:3000
      - IS_MINER=true
  
  node2:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - LISTEN_ADDR=node2:3001
      - BOOTSTRAP_NODES=node1:3000

  node3:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - LISTEN_ADDR=node3:3002
      - BOOTSTRAP_NODES=node2:3001