version: "3"

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - LISTEN_ADDR=gateway:6000
      
  node1:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - LISTEN_ADDR=node1:4000
      - API_LISTEN_ADDR=node1:8000
      - GATEWAY_ADDR=http://gateway:6000
      - CONSUL_SERVICE_ADDR=node1:10000
      - CONSUL_HTTP_ADDR=consul-server:8500
      - IS_MINER=true
    depends_on:
      - gateway
  
  node2:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - LISTEN_ADDR=node2:4001
      - API_LISTEN_ADDR=node2:8001
      - GATEWAY_ADDR=http://gateway:6000
      - CONSUL_SERVICE_ADDR=node2:10001
      - CONSUL_HTTP_ADDR=consul-server:8500
      - IS_MINER=false
      - BOOTSTRAP_NODES=node1:4000
    depends_on:
      - gateway

  node3:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    environment:
      - LISTEN_ADDR=node3:4002
      - API_LISTEN_ADDR=node3:8002
      - GATEWAY_ADDR=http://gateway:6000
      - CONSUL_SERVICE_ADDR=node3:10002
      - CONSUL_HTTP_ADDR=consul-server:8500
      - IS_MINER=false
      - BOOTSTRAP_NODES=node2:4001
    depends_on:
      - gateway

  node4:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    environment:
      - LISTEN_ADDR=node4:4003
      - API_LISTEN_ADDR=node4:8003
      - GATEWAY_ADDR=http://gateway:6000
      - CONSUL_SERVICE_ADDR=node4:10003
      - CONSUL_HTTP_ADDR=consul-server:8500
      - IS_MINER=false
      - BOOTSTRAP_NODES=node3:4002
    depends_on:
      - gateway

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    logging:
      driver: none
      
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./monitoring/alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    logging:
      driver: none

  grafana:
    image: grafana/grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ./monitoring/grafana/config.monitoring
    logging:
      driver: none
    restart: always

  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    restart: always
    volumes:
     - ./monitoring/consul/server.json:/consul/config/server.json:ro
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:latest
    container_name: consul-client
    restart: always
    volumes:
     - ./monitoring/consul/client.json:/consul/config/client.json:ro
    command: "agent"