global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node1"
    scrape_interval: 15s
    static_configs:
      - targets: ["node1:8000"]

  - job_name: "node2"
    scrape_interval: 15s
    static_configs:
      - targets: ["node2:8001"]

  - job_name: "node3"
    scrape_interval: 15s
    static_configs:
      - targets: ["node3:8002"]

  - job_name: "node4"
    scrape_interval: 15s
    static_configs:
      - targets: ["node4:8003"]
